FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.etl.txt /app/requirements.etl.txt
RUN pip install --no-cache-dir -r /app/requirements.etl.txt

COPY etl /app/etl

ENV PYTHONPATH=/app

CMD ["python", "-m", "etl.main"]
